# Bot Configuration
# Lines starting with # are comments
# Format: KEY: VALUE

PORT: emulator-5554
IGN: mynrd
MAP: 7-04
CHANNELS: 1,2,3

ADB_SHOW_TAP: true

# Combat Settings
IGNORE_NAME: false
USE_TELEPORT: false
ENGAGE_RED_BOSS: false
ENGAGE_GOLDEN_BOSS: true
RADIUS_SEARCH: 120
THRESHOLD_DMG_RED: 50
SKIP_NAMES: mynrd,okarun,rein,reinx,thor,thorjack,renn,baludoy,balu,marin,versus,kriox,ludoy,doy,balud,leatro,elchapo,tarugo

# General Settings
DEBUG: false
RESTART_AFTER_MINUTES: 60
ON_WALK_MODE_GO_TO_STARTING_POINT: false
RETRY_COUNT_READ_LIFE_FAILS: 2
DETECT_LOW_LIFE: false
TAP_ON_MAP_WHILE_WALKING: true

# Buffer Settings
IS_BUFFER: false
BUFFER:
BUFFER_MAP: CORRIDOR_OF_AGONY
BUFFER_COORDINATE:
DEBUFF_BEFORE_BUFF: true
BUFFER_WHITELIST_NAMES:
BUFFER_WHITELIST_GUILDS:

# Other Settings
AFK_MODE: false
DAWN_MODE: false
TAP_SKILL_CANCEL_ATTACK_COORDS: 84.0,76.0
